language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - dist
    - .cache
script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master